### ISSUE TITLE
Opacity overlaps when using grouped modules

### ISSUE THREAD

**Issue by rahatarmanahmed** [MalpenZibo/ashell#149]
Do something like this:

```toml
[modules]
right = ["Tray", ["Clock", "Settings"]]

```

and you get this:

![Image](https://github.com/user-attachments/assets/1a34a234-b391-44ae-b855-e6b8f27a332f)

I would have expected the opacity to be the same
