### ISSUE TITLE
Clock updates only every 5 seconds

### ISSUE THREAD

**Issue by rahatarmanahmed** [MalpenZibo/ashell#179]
If you have a clock config like this:

```toml
[clock]
# clock format see: https://docs.rs/chrono/latest/chrono/format/strftime/index.html
format =  "%A, %b %d – %T" 
```

Where the `%T` can show seconds, it only updates once every 5 seconds. It's exactly 5 seconds, because it shows like `:02`, `:07`, `:12`, `:17`, etc...
