### ISSUE TITLE
color of the number of the workspaces used

### ISSUE THREAD

**Issue by fiersik** [MalpenZibo/ashell#52]
I noticed that the color of the numbers of the workspaces used coincides with the color of the main background of the panel, which is why the number is poorly visible.

![image](https://github.com/user-attachments/assets/b8e72c9a-a26d-4aa3-80a3-662218708877)

Is there any way to change this color?

As I understand it, they both use backgroundColor.base, but it seems to me that this is not the best choice for numbers

**Comment by fiersik** [comment]
and then I don't understand what it's used for.:
    workspaceColors: 
      - "#fab387" 
      - "#b4befe"

**Comment by MalpenZibo** [comment]
There is probably a problem and it used the wrong foreground color.

The workspaceColors specify the background (or border) color to use in the workspace indicator. The first color is used for the workspace on the first monitor, the second color for the one on the second monitor, and so on.

If you can provide me with your current `Appearance` configuration I will do some tests.

**Comment by fiersik** [comment]
> If you can provide me with your current `Appearance` configuration I will do some tests.

Right now my configuration looks like this:

```
appearance:
    backgroundColor:
        base: "#0B0E1D"
        strong: "#6000c3"
        weak: "#333645"
    primaryColor:
        base: "#7E01FF"
        strong: "#7E01FF"
        weak: "#6000c3"
    secondaryColor:
        base: "#191d30"
        strong: "#12141f"
        weak: "#191d30"
    successColor: "#081BFE"
    dangerColor: "#e89b0b" 
    textColor: "#D8E2EA"
    workspaceColors:
    - "#ffffff"
```
