### ISSUE TITLE
Add calendar

### ISSUE THREAD

**Issue by JumpyLion87** [MalpenZibo/ashell#79]
Add a calendar that will be displayed when you click on the clock

**Comment by MalpenZibo** [comment]
It's in scope! I want to finish first the tray module but after that, the next big feature will be a panel for the clock with notifications, a calendar, and a weather indicator

**Comment by wvffle** [comment]
A nice thing to have in a calendar would be an ability to preview, add, modify and remove calendar events by reading and modifing the filesystem structure created by https://github.com/pimutils/vdirsyncer

**Comment by tank-bohr** [comment]
the temporary workaround

```toml
[modules]
center = [ "calendar", "Clock" ]
# ...
[[CustomModule]]
name = "calendar"
icon = ""
command = "zenity --calendar --title=\"Calendar\""
```
